#!/bin/bash

#read -p "Are you sure? " -n 1 -r
#echo    # (optional) move to a new line
#if [[ ! $REPLY =~ ^[Yy]$ ]]
#then
#    exit 1
#fi


cd client
docker rmi -f client
docker build -t client .
cd ..
cd nginx
docker rmi -f proxy
docker build -t proxy .

